
[env]
TERM = "xterm-256color"

[window]
padding.x = 16
padding.y = 14
decorations = "None"
startup_mode = "Maximized"

[terminal.shell]
program = "zellij"

[font]
size = 14.0

[font.bold]
# family = "MesloLGS Nerd Font Mono"
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
# family = "MesloLGS Nerd Font Mono"
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]

[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[terminal]
